### ISSUE TITLE
框架的正确性与可行性

### ISSUE THREAD

**Issue by Enpong** [DeepAQ/Autumn#2]
你好，请问你是怎么验证框架的可行性和正确性？

**Comment by DeepAQ** [comment]
1. 不是很理解你说的“可行性”具体指的是什么。这个项目既然已经被造出来了，肯定具备一定的可行性。
2. 对于框架的正确性，建议通过构造一个小型demo用来验证。当然，本项目主要还是以学习为目标，从来没有对正确性作出过保证😂。
